###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "vothanhdat",
    "password": "vothanhdat"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "vothanhdat",
    "password": "vothanhdat"
}

###
POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4M2IxNDI5MDhmMTI2ZjM2YzkzMDUiLCJpYXQiOjE2NjQzMzgwMzR9.nGGrnIBnSWuNebKmzNGmFoGpYFLXY_CRMXDLSSqWq-U

{
    "title": "React1",
    "description": "React1",
    "url": "react.com"
}

###
GET http://localhost:5000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4M2IxNDI5MDhmMTI2ZjM2YzkzMDUiLCJpYXQiOjE2NjM1ODQ2ODR9.pysUmGqvu1o50A9o5_nHrUwYY33N631jl22iBywPAcY



###
PUT http://localhost:5000/api/post/632849e392e74841948d1147
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzI4M2IxNDI5MDhmMTI2ZjM2YzkzMDUiLCJpYXQiOjE2NjM1ODQ2ODR9.pysUmGqvu1o50A9o5_nHrUwYY33N631jl22iBywPAcY

{
    "title": "Youtube",
    "description": "Youtube",
    "url": "youtube.com",
    "status": "LEARNING"
}


###
DELETE  http://localhost:5000/api/post/631dcfbac79a83c48abd9f58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFjODhiMDkzNjBjOTc0ZjI4Mzk4NmUiLCJpYXQiOjE2NjI4OTk3MzR9.GjOo6nvd0gZOd-ayuz6apx_vJ5GPETm9xJ620XwBXy8


###
POST http://localhost:5000/api/product
Content-Type: application/json

{
    "name": "Oppo A9",
    "price": "90",
    "tinyDes": "tốt",
    "fullDes": "rất tốt",
    "id_category": "6333d160de37f20e07927141"
}

###
GET http://localhost:5000/api/product?keyword=oppo

###
POST http://localhost:5000/api/category 
Content-Type: application/json

{
    "name": "Oppo"
}

###
GET  http://localhost:5000/api/filter/6333d160de37f20e07927144


###
GET http://localhost:5000/api/category 

###
GET http://localhost:5000/api/product

###
GET http://localhost:5000/api/filter/product/6333f0b2b797fcb83c01e576

###
POST http://localhost:5000/api/addCart 
Content-Type: application/json

{
    "userId": "63283b142908f126f36c9305",
    "id_product":"6333f0b2b797fcb83c01e576",
    "quantity": 0
}



###
GET http://localhost:5000/api/addCart/paying/63283b142908f126f36c9305
Content-Type: application/json


###
Post  http://localhost:5000/api/addCart 
Content-Type: application/json

{
    "userId": "63283b142908f126f36c9305",
    "id_product": "6333f26b44729dfd3f7b46b4",
    "quantity": 1,
    "pay": 0,
    "address": "no trang long"
}


###
Post  http://localhost:5000/api/addCart/Up   
Content-Type: application/json

{
    "userId": "63283b142908f126f36c9305",
    "id_product": "6333f26b44729dfd3f7b46b4"
}

###
Post  http://localhost:5000/api/addCart/Down 
Content-Type: application/json

{
    "userId": "63283b142908f126f36c9305",
    "id_product": "6333f26b44729dfd3f7b46b4"
}


###
Post  http://localhost:5000/api/addCart/pay
Content-Type: application/json

{
    "userId": "63283b142908f126f36c9305",
    "address": "356/13 no trang long"
}


###
GET http://localhost:5000/api/auth/all
Content-Type: application/json
